FootWear_OnlineStore/Models/Basket.cs
using FootWear_OnlineStore.OSDB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FootWear_OnlineStore.Models
{
    public class Basket
    {
        private string BasketID { get; set; }
        private const string BasketSessionKey = "BasketID";
        private StoreContext db = new StoreContext();

        private string GetBasketID()
        {
            if (HttpContext.Current.Session[BasketSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.Current.User.Identity.Name))
                {
                    HttpContext.Current.Session[BasketSessionKey] =
                        HttpContext.Current.User.Identity.Name;
                }
                else
                {
                    Guid tempBasketID = Guid.NewGuid();
                    HttpContext.Current.Session[BasketSessionKey] = tempBasketID.ToString();
                }
            }
            return HttpContext.Current.Session[BasketSessionKey].ToString();
        }

        public static Basket GetBasket()
        {
            Basket basket = new Basket();
            basket.BasketID = basket.GetBasketID();
            return basket;
        }

        public void AddToBasket(int productID, int quantity, int sizeID, int colourID)
        {
            var basketLine = db.BasketLines.FirstOrDefault(b => b.BasketID == BasketID 
                             && b.ProductID == productID
                             && b.SizeID == sizeID 
                             && b.ColourID == colourID);
            if (basketLine == null)
            {
                basketLine = new BasketLine
                {
                    ProductID = productID,
                    BasketID = BasketID,
                    Quantity = quantity,
                    DateCreated = DateTime.Now,
                    ColourID = colourID,
                    SizeID = sizeID
                };
                db.BasketLines.Add(basketLine);
            }
            else
            {
                basketLine.Quantity += quantity;
            }
            db.SaveChanges();
        }

        public void RemoveLine(int productID, int sizeID, int colourID)
        {
            var basketLine = db.BasketLines.FirstOrDefault(b => b.BasketID == BasketID 
                             && b.ProductID == productID
                             && b.SizeID == sizeID
                             && b.ColourID == colourID);
            if (basketLine != null)
            {
                db.BasketLines.Remove(basketLine);
            }
            db.SaveChanges();
        }

        public void UpdateBasket(List<BasketLine> lines)
        {
            foreach (var line in lines)
            {
                var basketLine = db.BasketLines.FirstOrDefault(b => b.BasketID == BasketID 
                                 && b.ProductID == line.ProductID
                                 && b.SizeID == line.SizeID
                                 && b.ColourID == line.ColourID);
                if (basketLine != null)
                {
                    if (line.Quantity == 0)
                    {
                        RemoveLine(line.ProductID, line.SizeID, line.ColourID);
                    }
                    else
                    {
                        basketLine.Quantity = line.Quantity;
                    }
                }
            }
            db.SaveChanges();
        }

        public void EmptyBasket()
        {
            var basketLines = db.BasketLines.Where(b => b.BasketID == BasketID);
            foreach (var basketLine in basketLines)
            {
                db.BasketLines.Remove(basketLine);
            }
            db.SaveChanges();
        }

        public List<BasketLine> GetBasketLines()
        {
            return db.BasketLines.Where(b => b.BasketID == BasketID).ToList();
        }

        public decimal GetTotalCost()
        {
            decimal basketTotal = decimal.Zero;
            if (GetBasketLines().Count > 0)
            {
                basketTotal = db.BasketLines.Where(b => b.BasketID == BasketID).Sum(b => b.Product.Price * b.Quantity);
            }
            return basketTotal;
        }

        public int GetNumberOfItems()
        {
            int numberOfItems = 0;
            if (GetBasketLines().Count > 0)
            {
                numberOfItems = db.BasketLines.Where(b => b.BasketID == BasketID).Sum(b => b.Quantity);
            }
            return numberOfItems;
        }

        public void MigrateBasket(string userName)
        {
            //find the current basket and store it in memory using ToList()
            var basket = db.BasketLines.Where(b => b.BasketID == BasketID).ToList();
            //find if the user already has a basket or not and store it in memory using //ToList()
            var usersBasket = db.BasketLines.Where(b => b.BasketID == userName).ToList();
            //if the user has a basket then add the current items to it
            if (usersBasket != null)
            {
                //set the basketID to the username
                string prevID = BasketID;
                BasketID = userName;
                //add the lines in anonymous basket to the user's basket
                foreach (var line in basket)
                {
                    AddToBasket(line.ProductID, line.Quantity, line.SizeID, line.ColourID);
                }
                //delete the lines in the anonymous basket from the database
                BasketID = prevID;
                EmptyBasket();
            }
            else
            {
                //if the user does not have a basket then just migrate this one
                foreach (var basketLine in basket)
                {
                    basketLine.BasketID = userName;
                }
                db.SaveChanges();
            }
            HttpContext.Current.Session[BasketSessionKey] = userName;
        }


        public decimal CreateOrderLines(int orderID)
        {
            decimal orderTotal = 0;
            var basketLines = GetBasketLines();
            foreach (var item in basketLines)
            {
                OrderLine orderLine = new OrderLine
                {
                    Product = item.Product,
                    ProductID = item.ProductID,
                    ProductName = item.Product.Name + " (" + item.Colour.Name + " " + item.Size.Region + "-" + item.Size.Measure + ")", /* add basket details for colour and size */
                    Quantity = item.Quantity,
                    UnitPrice = item.Product.Price,
                    OrderID = orderID
                };
                orderTotal += (item.Quantity * item.Product.Price);
                db.OrderLines.Add(orderLine);
            }
            db.SaveChanges();
            EmptyBasket();
            return orderTotal;
        }

    }
}

FootWear_OnlineStore/ViewModels/BasketViewModel.cs
using FootWear_OnlineStore.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FootWear_OnlineStore.ViewModels
{
    public class BasketViewModel
    {
        public List<BasketLine> BasketLines { get; set; }
        [Display(Name = "Basket Total:")]
        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal TotalCost { get; set; }
    }
}

FootWear_OnlineStore/Controllers/BasketController.cs
using FootWear_OnlineStore.Models;
using FootWear_OnlineStore.ViewModels;
using System.Web.Mvc;

namespace FootWear_OnlineStore.Controllers
{
    public class BasketController : Controller
    {
        // GET: Basket
        public ActionResult Index()
        {
            Basket basket = Basket.GetBasket();
            BasketViewModel viewModel = new BasketViewModel
            {
                BasketLines = basket.GetBasketLines(),
                TotalCost = basket.GetTotalCost()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToBasket(int id, int quantity, int sizeID, int colourID)
        {
            Basket basket = Basket.GetBasket();
            basket.AddToBasket(id, quantity, sizeID, colourID);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBasket(BasketViewModel viewModel)
        {
            Basket basket = Basket.GetBasket();
            basket.UpdateBasket(viewModel.BasketLines);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult RemoveLine(int id, int sizeID, int colourID)
        {
            Basket basket = Basket.GetBasket();
            basket.RemoveLine(id, sizeID, colourID);
            return RedirectToAction("Index");
        }

        public PartialViewResult Summary()
        {
            Basket basket = Basket.GetBasket();
            BasketSummaryViewModel viewModel = new BasketSummaryViewModel
            {
                NumberOfItems = basket.GetNumberOfItems(),
                TotalCost = basket.GetTotalCost()
            };
            return PartialView(viewModel);
        }
    }
}

FootWear_OnlineStore/Views/Basket/Index.cshtml
@model FootWear_OnlineStore.ViewModels.BasketViewModel

@{
    ViewBag.Title = "Your Basket";
}

<h2>@ViewBag.Title</h2>
@if (Model.BasketLines.Count() > 0)
{
    <div>
        @using (Html.BeginForm("UpdateBasket", "Basket"))
        {
            @Html.AntiForgeryToken();
            <input class="btn btn-sm btn-success" type="submit" value="Update Basket" />
            <hr />
            <div class="row floated-cols">
                <div class="col-md-4"><label>Item</label></div>
                <div class="col-md-2"><label>Quantity</label></div>
                <div class="col-md-2"><label>Price</label></div>
                <div class="col-md-2"><label>Subtotal</label></div>
            </div>
            <hr />
            for (int i = 0; i < Model.BasketLines.Count; i++)
            {
                <div class="row floated-cols">
                    <div class="col-md-4">
                            @Html.ActionLink(Model.BasketLines[i].Product.Name, "Details", "Products", new { id = Model.BasketLines[i].ProductID }, new { @class = "large-bold-text" })<br />
                            @if (Model.BasketLines[i].Product.ProductImageMappings != null && Model.BasketLines[i].Product.ProductImageMappings.Any())
                            {
                                <a href="@Url.Action("Details", "Products", new { id = Model.BasketLines[i].ProductID })">
                                    <img src="@(Url.Content(Constants.ProductThumbnailPath) + Model.BasketLines[i].Product.ProductImageMappings.OrderBy(pim => pim.ImageNumber).ElementAt(0).ProductImage.FileName)">
                                </a>
                            }
                            <p class="bold-text">Colour&nbsp;and&nbsp;Size:</p>
                            <p>@Html.DisplayFor(model => model.BasketLines[i].Colour.Name)&nbsp;@Html.DisplayFor(model => model.BasketLines[i].Size.Region)&nbsp;@Html.DisplayFor(model => model.BasketLines[i].Size.Measure)</p>
                    </div>
                    <div class="col-md-2">
                        @Html.HiddenFor(productID => Model.BasketLines[i].ProductID)
                        @Html.HiddenFor(sizeID => Model.BasketLines[i].SizeID)
                        @Html.HiddenFor(colourID => Model.BasketLines[i].ColourID)
                        @Html.TextBoxFor(quantity => Model.BasketLines[i].Quantity, new { @class = "form-control" })
                        <p>
                            @Html.ValidationMessageFor(quantity => Model.BasketLines[i].Quantity, "", new { @class = "text-danger" })
                        </p>
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayFor(price => Model.BasketLines[i].Product.Price)
                    </div>
                    <div class="col-md-2">
                        @((Model.BasketLines[i].Quantity * Model.BasketLines[i].Product.Price).ToString("c"))
                    </div>
                    <div class="col-md-1">
                        @Html.ActionLink("Remove", "RemoveLine", "Basket", new { id = Model.BasketLines[i].Product.ID, sizeID = Model.BasketLines[i].Size.ID, colourID = Model.BasketLines[i].Colour.ID }, null)
                    </div>
                </div>
                <hr />
            }
        }
        <div class="row floated-cols">
            <div class="col-md-6">
                @Html.DisplayNameFor(model => model.TotalCost)
            </div>
            <div class="col-md-2">
                @Html.DisplayFor(model => model.TotalCost)
            </div>
            <div class="col-md-2">
                @Html.ActionLink("Order Now", "Review", "Orders", null, new { @class = "btn btn-sm btn-success" })
            </div>
        </div>
    </div>
}
else
{
    <p>Your Basket is empty</p>
}
<div>
    @Html.ActionLink("Continue Shopping", "Index", "Products")
</div>
@section Scripts {
    @Scripts.Render("∼/bundles/jqueryval")
}

FootWear_OnlineStore/Views/Basket/Summary.cshtml
@model FootWear_OnlineStore.ViewModels.BasketSummaryViewModel

<ul class="nav navbar-nav navbar-right">
    <li>
        @Html.ActionLink("Your basket: " + Model.NumberOfItems + " items(s) " + HttpUtility.HtmlDecode(Html.DisplayFor(model => Model.TotalCost).ToString()), "Index", "Basket")
    </li>
</ul>