FootWear_OnlineStore/Models/Colour.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FootWear_OnlineStore.Models
{
    public partial class Colour
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public virtual ICollection<ProductColour> Products { get; set; }
    }
}

FootWear_OnlineStore/Models/Product.cs
using System.Collections.Generic;

namespace FootWear_OnlineStore.Models
{
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int? CategoryID { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
        public virtual ICollection<ProductColour> ProductColours { get; set; }
        public virtual ICollection<ProductImageMapping> ProductImageMappings { get; set; }
    }
}

FootWear_OnlineStore/Models/Size.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FootWear_OnlineStore.Models
{
    public partial class Size
    {
        public int ID { get; set; }
        public string Region { get; set; }
        public int Measure { get; set; }
        public virtual ICollection<ProductSize> Products { get; set; }
    }
}

FootWear_OnlineStore/ViewModels/ProductViewModel.cs
using FootWear_OnlineStore.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace FootWear_OnlineStore.ViewModels
{
    public class ProductViewModel
    {
        // Added the images select list and the product models fields (as ref Chapter Managing product Images)
        public int ID { get; set; }
        [Required(ErrorMessage = "The product name cannot be blank")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter a product name between 3 and 50 characters in length")]
        [RegularExpression(@"^[a-zA-Z0-9'-'\s]*$", ErrorMessage = "Please enter a product name made up of letters and numbers only")]
        public string Name { get; set; }
        [Required(ErrorMessage = "The product description cannot be blank")]
        [StringLength(200, MinimumLength = 10, ErrorMessage = "Please enter a product description between 10 and 200 characters in length")]
        [RegularExpression(@"^[,;a-zA-Z0-9'-'\s]*$", ErrorMessage = "Please enter a product description made up of letters and numbers only")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required(ErrorMessage = "The price cannot be blank")]
        [Range(0.10, 10000, ErrorMessage = "Please enter a price between 0.10 and 10000.00")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:c}")]
        [RegularExpression("[0-9]+(\\.[0-9][0-9]?)?", ErrorMessage = "The price must be a number up to two decimal places")]
        public decimal Price { get; set; }

        [Display(Name = "Category")]
        public int CategoryID { get; set; }
        public SelectList CategoryList { get; set; }
        public List<SelectList> ImageLists { get; set; }
        public string[] ProductImages { get; set; }

        // Original ViewModel for Colours and Sizes for product
        public Product Product { get; set; }
        public ProductColour ProductColour { get; set; }
        public ProductSize ProductSize { get; set; }
        public IEnumerable<SelectListItem> Colours { get; set; }
        public IEnumerable<SelectListItem> Sizes { get; set; }
        // Added 9 Jan 2019 - Display for Colours and Sizes using this ViewModel
        public int SizeID { get; set; }
        public int ColourID { get; set; }
        [Display(Name = "Available Colours")]
        public IEnumerable<SelectListItem> ProductColours { get; set; }
        [Display(Name = "Available Sizes")]
        public IEnumerable<SelectListItem> ProductSizes { get; set; }

    }
}

FootWear_OnlineStore/Controllers/ColoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FootWear_OnlineStore.Models;
using FootWear_OnlineStore.OSDB;

namespace FootWear_OnlineStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ColoursController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Colours
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Colours.OrderBy(c => c.Name).ToList());
        }

        // GET: Colours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colour colour = db.Colours.Find(id);
            if (colour == null)
            {
                return HttpNotFound();
            }
            return View(colour);
        }

        // GET: Colours/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Colour colour)
        {
            if (ModelState.IsValid)
            {
                db.Colours.Add(colour);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(colour);
        }

        // GET: Colours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colour colour = db.Colours.Find(id);
            if (colour == null)
            {
                return HttpNotFound();
            }
            return View(colour);
        }

        // POST: Colours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Colour colour)
        {
            if (ModelState.IsValid)
            {
                db.Entry(colour).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(colour);
        }

        // GET: Colours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colour colour = db.Colours.Find(id);
            if (colour == null)
            {
                return HttpNotFound();
            }
            return View(colour);
        }

        // POST: Colours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Colour colour = db.Colours.Find(id);
            db.Colours.Remove(colour);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FootWear_OnlineStore/Controllers/ProductsController.cs
using FootWear_OnlineStore.Models;
using FootWear_OnlineStore.OSDB;
using FootWear_OnlineStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Routing;
using PagedList;

namespace FootWear_OnlineStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private StoreContext db = new StoreContext();

        // GET: Products
        [AllowAnonymous]
        public ActionResult Index(string category, string search, string sortBy, int? page)
        {
            //Instantiate a new view model      
            // Data migration and seeding enabled (at CompoundKeysProductColoursAndSizes) 
            // Added 9 Jan 2019 -  Sorting by prices, and paging at products index.
            // Lab05 completed 9 Jan 2019
            // Added 11 Jan 2019 - RolesManager with Admin user and "two context" database migrations with "StoreConfiguration" for products and store 
            // Addedd 12 Jan 2019 ProductImage table and multiple image uploading action ProductImages Controller.
            // Added 13 jan 2019: associate image to products and productcontroller update 
            // Added 14 Jan 2019: routing maps for Products index with category filtering and page # in RoutesConfig (As done in Lab06a)
            // Added 15 Jan 2019: Lab06b check for image upload, Lab06c check for multiple image uploads. Added Custom error page for over 20MB
            //                    Note: 15 Jan 2019 - added Lab06c the check for  request length and a custom error message ( see Chapter Managing Images )
            // Added 16 Jan 2019: Associate images to products with the images being able to belong to more than one product as in Lab06d
            //                    Created partial view for editing and creating products.
            // Added 16 Jan 2019: Fixing the Navigation Bar Style Issues as in Chapter Authentication and Authorisation to fix page header.
            // Added 17 Jan 2019: Admin ViewModels for Roles and RolesAdminController and AdminController
            // Added 17 Jan 2019: Updated Identity user with Name, Address and date of birth fields. 
            //                    Migrate DApplicationDbContext using named context "Configuration"
            // Added 17 Jan 2019: UsersAdminController as in Chapter Authentication and Authorisation
            // Added 17 Jan 2019: User self registration and user view and edit their details. Allow Users to Reset Their Passwords
            // Added 17 Jan 2019: Authorization for Product and Category Administration and friendlier ReturnUrl redirection for Login and Register user.
            // Added 20 Jan 2019: Baskets model with Model Binding to a List or an Array, and Basket item removal/update
            // Added 21 Jan 2019: Basket Summary and Migrating a Basket When a User Logs In or Registers (see AccountController, Login action.)
            // Added 27 Jan 2019: Ref: Chapter 9 - Add Order and OrderLines, View Orders and Displaying Order Data.
            //                    Place an order and Create Order from basket review. Saving an Order to the Database.
            //                    Updating Product Deletion to Avoid Foreign Key Conflicts.
            //                    Searching Orders to filter by search text. Sorting Orders in index page.
            //                    Made Home page with Best selling shoes (top 4).
            // Added 28 Jan 2019: Tutorial 8 CSS Usage in online store. Ref:Chapter 14 Stylesheets store.css and reset.css added for new styling of web site. 
            // Added 4 Feb 2019: Top Image and seach box for site and navigation styles (as in Chapter 17)
            // Added 8 Feb 2019: Responsize styles for smaller devices. Tidy up the buttons and tables for small devices.

            ProductIndexViewModel viewModel = new ProductIndexViewModel(); 
            var products = db.Products.Include(p => p.Category);

            // Filter product list to seach
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Name.Contains(search) ||
                    p.Description.Contains(search) ||
                    p.Category.Name.Contains(search) );
                viewModel.Search = search;
            }

            viewModel.CatsWithCount = from matchingProducts in products
                                      where matchingProducts.CategoryID != null
                                      group matchingProducts by
                                      matchingProducts.Category.Name into catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          ProductCount = catGroup.Count()
                                      };

            if (!String.IsNullOrEmpty(category)) {
                products = products.Where(p => p.Category.Name == category);
                viewModel.Category = category; // Added 9 Jan 2019 for PagedList to remember category in pages
            }

            // Added: Rodney 9 Jan 2019 sort the results
            switch (sortBy)
            {
                case "price_lowest":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price_highest":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    // Added 9 Jan 2019 for PagedList as default order by
                    products = products.OrderBy(p => p.Name);
                    break;
            }
            int currentPage = (page ?? 1);
            viewModel.Products = products.ToPagedList(currentPage, Constants.PageItems);
            viewModel.SortBy = sortBy; // Added 9 Jan 2019 for PagedList to remember the sorted by 

            // Added: Rodney 9 Jan 2019 sort the results
            viewModel.Sorts = new Dictionary<string, string>
            {
                {"Price low to high", "price_lowest" },
                {"Price high to low", "price_highest" }
            };


            return View(viewModel);
        }

        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.ID = product.ID;
            viewModel.Product = product;
            productColourAndSizeToVM(viewModel, product.ID);
            return View(viewModel);
            //return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            // Added 13 Jan 2019 - use ProductViewModel
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.CategoryList = new SelectList(db.Categories, "ID", "Name");
            viewModel.ImageLists = new List<SelectList>();
            for (int i = 0; i < Constants.NumberOfProductImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.ProductImages, "ID", "FileName"));
            }
            return View(viewModel);
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel viewModel)
        {
            Product product = new Product();
            product.Name = viewModel.Name;
            product.Description = viewModel.Description;
            product.Price = viewModel.Price;
            product.CategoryID = viewModel.CategoryID;
            product.ProductImageMappings = new List<ProductImageMapping>();
            //get a list of selected images without any blanks
            string[] productImages = viewModel.ProductImages.Where(pi =>
                !string.IsNullOrEmpty(pi)).ToArray();
            for (int i = 0; i < productImages.Length; i++)
            {
                product.ProductImageMappings.Add(new ProductImageMapping
                {
                    ProductImage = db.ProductImages.Find(int.Parse(productImages[i])),
                    ImageNumber = i
                });
            }
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            viewModel.CategoryList = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            viewModel.ImageLists = new List<SelectList>();
            for (int i = 0; i < Constants.NumberOfProductImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.ProductImages, "ID", "FileName",
                        viewModel.ProductImages[i]));
            }
            return View(viewModel);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
 
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.CategoryList = new SelectList(db.Categories, "ID", "Name", product.CategoryID);

FootWear_OnlineStore/Views/Products/AddColour.cshtml
@model FootWear_OnlineStore.ViewModels.ProductViewModel

@{
    ViewBag.Title = "Add Colour";
}

<h2>Add Colour</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Product Colour</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.ProductColour.ProductID, new { Value = Model.Product.ID }) 
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductColour.ColourID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(vm => vm.ProductColour.ColourID, Model.Colours, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductColour.ColourID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
    @Html.Raw(" | ")
    @Html.ActionLink("Product Colours", "Colours", new { id = Model.Product.ID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FootWear_OnlineStore/Views/Products/AddSize.cshtml
@model  FootWear_OnlineStore.ViewModels.ProductViewModel

@{
    ViewBag.Title = "Add Size";
}

<h2>Add Size</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Product Size</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.ProductSize.ProductID, new { Value = Model.Product.ID })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductSize.SizeID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(vm => vm.ProductSize.SizeID, Model.Sizes, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductSize.SizeID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
    @Html.Raw(" | ")
    @Html.ActionLink("Product Sizes", "Sizes", new { id = Model.Product.ID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FootWear_OnlineStore/Views/Products/Colours.cshtml
@model IEnumerable<FootWear_OnlineStore.Models.ProductColour>

@{
    ViewBag.Title = "Colours";
}

<h2>Colours</h2>

<p>
    @Html.ActionLink("Add Colour", "AddColour", new { id = ViewBag.ProductID })
</p>
<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Product.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.First().Product.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Product.Description)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.First().Product.Description)
    </dd>
</dl>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Colour.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Colour.Name)
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteColour", new { id = item.ProductID, colour = item.ColourID })
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Back to List", "Index")
    @Html.Raw(" | ")
    @Html.ActionLink("Product Details", "Details", new { id = ViewBag.ProductID })
</div>

FootWear_OnlineStore/Views/Products/Details.cshtml
@model FootWear_OnlineStore.ViewModels.ProductViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Price)
        </dd>
        @if (Model.Product.ProductImageMappings != null && Model.Product.ProductImageMappings.Any())
        {
            <dt></dt>
            <dd>
                <img src="@(Url.Content(Constants.ProductImagePath) +
                        Model.Product.ProductImageMappings.OrderBy(pim =>
                        pim.ImageNumber).ElementAt(0).ProductImage.FileName)">
            </dd>
            <dt></dt>
            <dd>
                @*<div class="row">*@
                @foreach (var item in Model.Product.ProductImageMappings.OrderBy(pim =>
                        pim.ImageNumber))
                {
                    @*<div class="col-md-3">*@
                    <a href="@(Url.Content(Constants.ProductImagePath) +
                        item.ProductImage.FileName)">
                        <img src="@(Url.Content(Constants.ProductThumbnailPath) +
                        item.ProductImage.FileName)">
                    </a>
                    @*</div>*@
                }
                @*</div>*@
            </dd>
        }
    </dl>
    @using (Html.BeginForm("AddToBasket", "Basket"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)
        <dl class="dl-horizontal">
            <dt>
                @*            @Html.DisplayNameFor(model => model.ProductColours)*@
                @Html.LabelFor(model => model.ColourID, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd>
                @*            @Html.DropDownListFor(model => model.ProductColours, null, htmlAttributes: new { @class = "form-control", @size = Model.ProductColours.Count() })*@
                @Html.DropDownListFor(vm => vm.ColourID, Model.ProductColours, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ColourID, "", new { @class = "text-danger" })
            </dd>
            <dt>
                @*            @Html.DisplayNameFor(model => model.ProductSizes)*@
                @Html.LabelFor(model => model.SizeID, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd>
                @*            @Html.DropDownListFor(model => model.ProductSizes, null, htmlAttributes: new { @class = "form-control", @size = Model.ProductSizes.Count() })*@
                @Html.DropDownListFor(vm => vm.SizeID, Model.ProductSizes, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SizeID, "", new { @class = "text-danger" })
            </dd>
            <dt>
                Quantity:
            </dt>
            <dd>
                @Html.DropDownList("quantity", Enumerable.Range(1, 10).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
                <input type="submit" class="btn btn-primary btn-xs" value="Add to Basket">
            </dd>
        </dl>
    }
</div>
<p>
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Product.ID })
        @Html.Raw(" | ")
        @Html.ActionLink("Add Sizes", "Sizes", new { id = Model.Product.ID })
        @Html.Raw(" | ")
        @Html.ActionLink("Add Colours", "Colours", new { id = Model.Product.ID })
        @Html.Raw(" | ")
    }
    @Html.ActionLink("Back to List", "Index")
</p>


@section scripts {
    <script>
        $(document).ready(function () {
            $('a>img').click(function (evt) {
                evt.preventDefault();
                var thumbnailAddress = $(this).parent().attr('href');
                var mainImage = $('dd > img'); // Only the one selector for this combination of tags
                mainImage.attr('src', thumbnailAddress);
            });
        });
    </script>
}

FootWear_OnlineStore/Views/Products/Index.cshtml
@model FootWear_OnlineStore.ViewModels.ProductIndexViewModel
@using PagedList.Mvc

@{
    ViewBag.Title = "Shoe Products";
}

<h2>@ViewBag.Title</h2>

<p>
    @* Added 9 Jan 2019 message for seach result item count if a seach is active *@
    @(String.IsNullOrWhiteSpace(Model.Search) ? "Showing all" : "You search for " + Model.Search + " found") @Model.Products.TotalItemCount products
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        @Html.ActionLink("Create New", "Create")
    }
        @using (Html.BeginRouteForm("ProductsIndex", FormMethod.Get))
        {
            <label>Filter by category:</label>
            @Html.DropDownListFor(vm => vm.Category, Model.CatFilterItems, "All")
            @* Added: 9 Jan 2019 sort by price *@
            <label>Sort By:</label>
            @Html.DropDownListFor(vm => vm.SortBy, new SelectList(Model.Sorts, "Value", "Key"), "Default")
            <input type="submit" value="Filter" />
            <input type="hidden" name="Search" id="Search" value="@Model.Search" />
        }
    </p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Products.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Products.First().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Products.First().Price)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Products)
    {
    <tr class="row">
        <td>
            @if (item.ProductImageMappings != null && item.ProductImageMappings.Any())
            {
                <a href="@Url.Action("Details", new { id = item.ID})">
                    <img src="@(Url.Content(Constants.ProductImagePath) +
                        item.ProductImageMappings.OrderBy(pim =>
                        pim.ImageNumber).ElementAt(0).ProductImage.FileName)">
                </a>
            }
        </td>
        <td data-th="@Html.DisplayNameFor(model => model.Category)">
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td data-th="@Html.DisplayNameFor(model => model.Products.First().Name)">
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td data-th="@Html.DisplayNameFor(model => model.Products.First().Description)">
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td data-th="@Html.DisplayNameFor(model => model.Products.First().Price)">
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                @Html.Raw(" | ")
                @Html.ActionLink("Add Sizes", "Sizes", new { id = item.ID })
                @Html.Raw(" | ")
                @Html.ActionLink("Add Colours", "Colours", new { id = item.ID })
                @Html.Raw(" | ")
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                @Html.Raw(" | ")
            }
            @Html.ActionLink("Details", "Details", new { id = item.ID })
        </td>
    </tr>
    }

</table>
@* Added 9 Jan 2019 PagedList control buttons *@
<div>
    Page @(Model.Products.PageCount < Model.Products.PageNumber ? 0 : Model.Products.PageNumber) of @Model.Products.PageCount
    @Html.PagedListPager(Model.Products, page => Url.Action("Index", new
{
    category = @Model.Category,
    Search = @Model.Search,
    sortBy = @Model.SortBy,
    page
}))
</div>